"use client";
import { useMemo, useState } from "react";

type Zip={zip:string;area:string;income:number;rent:number;rentGrowth:number;incomeGrowth:number;x:number;y:number};
const ZIPS:Zip[]=[
 ["92037","La Jolla",145000,3800,.045,.04,28,17],["92109","Pacific Beach",95000,3100,.055,.036,31,28],["92117","Clairemont",81000,2550,.052,.034,45,23],["92111","Linda Vista",76000,2450,.055,.032,48,35],["92116","Normal Heights",69000,2350,.061,.03,59,43],["92115","Rolando",61000,2300,.065,.03,76,47],["92104","North Park",72000,2400,.062,.031,54,49],["92105","City Heights",47000,1950,.06,.02,68,52],["92114","Encanto",58000,2200,.06,.03,76,60],["92102","Golden Hill",52000,2100,.065,.025,56,60],["92101","Downtown",68000,2450,.07,.03,45,67],["92113","Logan Heights",45000,1900,.055,.02,58,69],["92126","Mira Mesa",84000,2600,.05,.035,68,14],["92154","Otay Mesa",53000,2050,.06,.025,72,83],["92173","San Ysidro",44000,1850,.055,.02,61,92]
].map(([zip,area,income,rent,rentGrowth,incomeGrowth,x,y])=>({zip,area,income,rent,rentGrowth,incomeGrowth,x,y})) as Zip[];
const MAP_SHAPES:Record<string,{d:string;lx:number;ly:number}>={
 "92037":{d:"M176 91 260 64 314 98 300 159 244 190 185 158Z",lx:242,ly:130},
 "92109":{d:"M185 158 244 190 287 228 267 286 202 272 169 220Z",lx:225,ly:226},
 "92117":{d:"M300 159 392 140 431 203 397 257 287 228 244 190Z",lx:349,ly:202},
 "92126":{d:"M260 64 430 48 548 91 517 161 431 203 392 140 314 98Z",lx:427,ly:112},
 "92111":{d:"M287 228 397 257 421 311 350 345 267 286Z",lx:345,ly:286},
 "92116":{d:"M397 257 480 242 522 291 489 338 421 311Z",lx:460,ly:289},
 "92104":{d:"M421 311 489 338 477 393 394 405 350 345Z",lx:431,ly:357},
 "92115":{d:"M480 242 570 221 616 276 585 342 522 291Z",lx:550,ly:279},
 "92105":{d:"M489 338 585 342 596 404 520 432 477 393Z",lx:535,ly:383},
 "92102":{d:"M350 345 394 405 386 454 309 446 288 390Z",lx:353,ly:405},
 "92101":{d:"M267 286 350 345 288 390 234 366 218 315Z",lx:282,ly:337},
 "92114":{d:"M585 342 656 337 687 407 616 455 596 404Z",lx:626,ly:397},
 "92113":{d:"M288 390 386 454 462 480 421 522 318 510 250 455Z",lx:351,ly:469},
 "92154":{d:"M462 480 616 455 687 407 708 494 642 537 421 522Z",lx:568,ly:501},
 "92173":{d:"M318 510 421 522 642 537 603 552 338 552 280 535Z",lx:445,ly:536}
};
const runway=(b:number,r:number,i:number)=>b>=.5?0:(1+r)/(1+i)<=1?Infinity:12*Math.log(.5/b)/Math.log((1+r)/(1+i));
const months=(n:number)=>!Number.isFinite(n)||n>600?"No crossing":n<1?"Now":`${Math.round(n)} mo`;
const risk=(n:number)=>n<=12?"critical":n<=48?"warning":"stable";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export default function Home(){
 const [selected,setSelected]=useState("92105"),[wage,setWage]=useState(8),[cap,setCap]=useState(3),[voucher,setVoucher]=useState(50),[policy,setPolicy]=useState(false);
 const results=useMemo(()=>ZIPS.map(z=>{const burden=z.rent*12/z.income,before=runway(burden,z.rentGrowth,z.incomeGrowth),gap=Math.max(burden-.3,0),adjusted=(burden-gap*voucher/100)/(1+wage/100),after=runway(adjusted,Math.min(z.rentGrowth,cap/100),z.incomeGrowth);return{...z,burden,before,after,gain:after-before}}).sort((a,b)=>a.before-b.before),[wage,cap,voucher]);
 const active=results.find(z=>z.zip===selected)??results[0], shown=policy?active.after:active.before;
 const median=(key:"before"|"after")=>[...results].sort((a,b)=>a[key]-b[key])[Math.floor(results.length/2)][key];
 const movedBeyondUrgent=results.filter(z=>z.before<=24&&z.after>24).length;
 const resetScenario=()=>{setWage(8);setCap(3);setVoucher(50);setPolicy(false)};
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brandMark">P</span><span>Priceout Collective</span></a><nav><a href="#risk">Risk map</a><a href="#interventions">Interventions</a><a href="#method">Method</a></nav><span className="eventTag">BUILDING FOR GOOD · UCSD</span></header>
  <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">San Diego affordability observatory</p><h1>Before rent takes <em>half</em> the household.</h1><p className="lede">A ZIP-level early-warning system that turns a widening rent–income gap into something decision-makers can act on: <strong>time remaining.</strong></p><div className="heroActions"><a className="button primary" href="#risk">Explore the runway</a><a className="button ghost" href="#interventions">Test a policy</a></div></div><aside className="signalCard"><p className="cardLabel">Why this exists</p><div className="signalNumber">3</div><p className="signalText">prototype areas have twelve months or less on the current path.</p><div className="signalRule"><span/></div><p className="fine"><b>Prototype data.</b> The tool is ready; organizer data must replace these illustrative values before judging.</p></aside></section>
  <section className="definitionBand"><p><span>THE SIMPLE IDEA</span> Find where pressure is rising fastest, then test which intervention buys the most time back.</p></section>
  <section className="demoPath" aria-label="Thirty second demo path"><span>30-SECOND DEMO</span><p><b>1</b> Pick an area</p><i>→</i><p><b>2</b> Change a lever</p><i>→</i><p><b>3</b> See the time gained</p></section>
  <section className="section" id="risk"><div className="sectionHead"><div><p className="eyebrow">01 · Locate the pressure</p><h2>Where time is running out</h2><p className="sectionIntro"><b>Why this view:</b> a map makes unequal neighborhood pressure visible immediately. Select any area to see what drives its result.</p></div><div className="viewToggle"><button className={!policy?"active":""} onClick={()=>setPolicy(false)}>Today</button><button className={policy?"active":""} onClick={()=>setPolicy(true)}>With policy</button></div></div>
   <div className="riskGrid"><div className="mapPanel"><div className="mapTitle"><span>San Diego pressure map</span><small>Select a ZIP region</small></div><div className="mapCanvas mapRebuilt"><svg className="zipMap" viewBox="0 0 760 570" role="img" aria-labelledby="map-title map-desc"><title id="map-title">Prototype San Diego housing pressure map</title><desc id="map-desc">Interactive schematic ZIP regions colored by modeled time until the pressure threshold.</desc><rect className="mapWater" width="760" height="570"/><path className="shoreGlow" d="M170 20C157 95 151 160 161 216C173 279 201 321 214 382C224 431 234 487 280 535"/><path className="shoreLine" d="M170 20C157 95 151 160 161 216C173 279 201 321 214 382C224 431 234 487 280 535"/><g className="mapRoutes"><path d="M275 74C350 155 391 249 421 522"/><path d="M193 220C343 228 475 247 616 276"/><path d="M235 365C371 368 518 386 687 407"/></g>{results.map(z=>{const shape=MAP_SHAPES[z.zip],value=policy?z.after:z.before;return <g key={z.zip} role="button" tabIndex={0} className={`zipRegion ${risk(value)} ${selected===z.zip?"selected":""}`} onClick={()=>setSelected(z.zip)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(z.zip)}}} aria-label={`${z.area}, ZIP ${z.zip}, ${months(value)} runway`}><path d={shape.d}/><text x={shape.lx} y={shape.ly-5}>{z.area}</text><text className="zipRegionMeta" x={shape.lx} y={shape.ly+11}>{z.zip} · {months(value)}</text></g>})}<text className="waterName" x="52" y="300">PACIFIC OCEAN</text><g className="mapNorth"><text x="714" y="48">N</text><path d="M718 76V55M718 55 712 64M718 55 724 64"/></g></svg><div className="mapSelection"><span>Selected</span><strong>{active.area}</strong><small>{active.zip} · {months(shown)} runway</small></div><div className="mapLegend"><span><i className="critical"/>0–12 mo</span><span><i className="warning"/>13–48 mo</span><span><i className="stable"/>49+ mo</span></div><p className="mapDisclaimer">Prototype topology—not official ZIP boundaries.</p></div></div>
    <aside className="detailPanel"><div className="detailTop"><div><p className="cardLabel">Selected area</p><h3>{active.area}</h3><p className="zipLabel">ZIP {active.zip}</p></div><span className={`riskPill ${risk(shown)}`}>{risk(shown)}</span></div><div className="runwayFigure"><strong>{months(shown)}</strong><span>runway index</span></div>{policy&&<p className="gainCallout">This scenario adds {Number.isFinite(active.gain)?`${Math.max(0,Math.round(active.gain))} modeled months`:"an open-ended runway"}.</p>}<dl className="metrics"><div><dt>Median gross rent</dt><dd>{money(active.rent)}<small>/mo</small></dd></div><div><dt>Median household income</dt><dd>{money(active.income)}<small>/yr</small></dd></div><div><dt>Area pressure ratio</dt><dd>{(active.burden*100).toFixed(1)}%</dd></div><div><dt>Annual growth gap</dt><dd>+{((active.rentGrowth-active.incomeGrowth)*100).toFixed(1)}<small> pts</small></dd></div></dl><p className="detailNote">Ratio of area medians. It should not be interpreted as the burden of a typical renter household.</p></aside></div>
  </section>
  <section className="section intervention" id="interventions"><div className="sectionHead"><div><p className="eyebrow">02 · Change the trajectory</p><h2>What buys time back?</h2><p className="sectionIntro"><b>Why this view:</b> the sliders turn broad policy ideas into comparable scenarios. Move one lever and see the same model recalculate every area.</p></div><div className="scenarioActions"><button className="button reset compact" onClick={resetScenario}>Reset</button><button className="button primary compact" onClick={()=>{setPolicy(true);document.getElementById("risk")?.scrollIntoView({behavior:"smooth"})}}>Show on map</button></div></div>
   <div className="leverGrid"><label className="leverCard wage"><span className="leverIndex">A</span><span className="leverName">Household income lift</span><strong>+{wage}%</strong><input aria-label="Household income lift" type="range" min="0" max="20" value={wage} onChange={e=>setWage(+e.target.value)}/><small>Modeled as a one-time income increase</small></label><label className="leverCard cap"><span className="leverIndex">B</span><span className="leverName">Annual rent-growth cap</span><strong>{cap}%</strong><input aria-label="Annual rent growth cap" type="range" min="1" max="8" step=".5" value={cap} onChange={e=>setCap(+e.target.value)}/><small>Only reduces growth above the selected cap</small></label><label className="leverCard voucher"><span className="leverIndex">C</span><span className="leverName">Voucher gap coverage</span><strong>{voucher}%</strong><input aria-label="Voucher gap coverage" type="range" min="0" max="100" step="5" value={voucher} onChange={e=>setVoucher(+e.target.value)}/><small>Share of burden above the 30% affordability line</small></label></div>
   <div className="outcomes" id="results"><div><span>Median runway</span><strong>{months(median("before"))}</strong><small>today</small></div><div className="arrow">→</div><div className="positive"><span>Median runway</span><strong>{months(median("after"))}</strong><small>with this scenario</small></div><div><span>Areas moved</span><strong>{movedBeyondUrgent}</strong><small>beyond 24 months</small></div></div>
   <p className="decisionNote"><span>Decision signal</span> Under the selected assumptions, {movedBeyondUrgent} of the prototype’s urgent areas move beyond the two-year pressure window.</p>
   <div className="rankingPanel"><div className="rankingHead"><h3>Highest-priority prototype areas</h3><span>Current path → scenario</span></div><div className="rankRows">{results.slice(0,5).map((z,i)=><button key={z.zip} className="rankRow" onClick={()=>{setSelected(z.zip);setPolicy(true);document.getElementById("risk")?.scrollIntoView({behavior:"smooth"})}}><span className="rank">{String(i+1).padStart(2,"0")}</span><span className="rankName"><strong>{z.area}</strong><small>{z.zip}</small></span><span className="bars"><i className="before" style={{width:`${Math.min(100,z.before/1.8)}%`}}/><i className="after" style={{width:`${Math.min(100,z.after/1.8)}%`}}/></span><span className="rankValue"><strong>{months(z.after)}</strong><small>{months(z.before)} current</small></span></button>)}</div></div>
  </section>
  <section className="section method" id="method"><div className="methodIntro"><p className="eyebrow">03 · Evidence</p><h2>Simple on purpose.<br/>Careful by design.</h2><p>HUD defines housing costs above 30% of household income as cost burden and above 50% as severe cost burden. Priceout borrows the 50% line, but its ZIP-level ratio of medians is an index—not HUD’s household measure.</p></div><div className="methodSteps"><article><span>01</span><h3>Area baseline</h3><p>Annual median gross rent ÷ median household income creates a comparable ZIP-level pressure ratio.</p></article><article><span>02</span><h3>Runway scenario</h3><p>The current rent–income growth gap is extended until the area ratio reaches 50%.</p></article><article><span>03</span><h3>Policy test</h3><p>The assumptions change, then the exact same formula runs again for a clean comparison.</p></article></div><div className="technicalProof"><div><strong>One shared CSV</strong><span>Map and calculator stay aligned</span></div><div><strong>Deterministic math</strong><span>No black-box prediction</span></div><div><strong>Reproducible pipeline</strong><span>Raw data → model → demo</span></div></div><div className="caveat"><strong>Before judging</strong><p>Replace the illustrative rows with the organizer dataset; use renter-household income and gross rent from comparable years; retain ACS margins of error; document growth assumptions. <a href="https://www.huduser.gov/portal/datasets/cp/CHAS/bg_chas.html" target="_blank" rel="noreferrer">HUD burden definitions</a> · <a href="https://www.census.gov/data/developers/data-sets/acs-5year.html" target="_blank" rel="noreferrer">ACS 5-year guidance</a></p></div></section>
  <footer><div><span className="brand"><span className="brandMark">P</span><span>Priceout Collective</span></span><p>Building for Good Hackathon · Cost-of-Living Affordability</p></div><p>Built to make the cost of waiting visible.</p></footer>
 </main>
}
